Document: cms
Title: Debian cms Manual
Author: <insert document author here>
Abstract: This manual describes what cms is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cms/cms.sgml.gz

Format: postscript
Files: /usr/share/doc/cms/cms.ps.gz

Format: text
Files: /usr/share/doc/cms/cms.text.gz

Format: HTML
Index: /usr/share/doc/cms/html/index.html
Files: /usr/share/doc/cms/html/*.html
